---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
