# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qr/KZifZazvyD5yG06U9i7y8LnM=,iv:4ItROm9oZiohwaasZ1IKHNf4cE/i9ZmdMKG3kIlmlS8=,tag:Cc28CFmlvxx35j8rCcK/qw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:P3iGOK6Qa2aTFzk87K10+e9/xDGq2YXVkISUwUpsgXZkQcBOfw==,iv:D6Mk50VYZ9UgFZ3HJZ+Bp0tc8q8J1fsiFT4PZSTT2GI=,tag:eevOrWLgnMfXhHLl4C6jGw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:y2Nx2y4CZCd795lTW74=,iv:9opK7ERmFpWdrftNUZszkvYHRWr996746ZRVgrgFUiw=,tag:p2LcuheLsDrlHAnLgFxNSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qhgwj6mzm5z5frl3zxr933l5qgznk7x6hcpaejhxja8q8a2vuwq2wdax2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGloOWpVOGZ2aVdqb0cz
            RFNyK0ZzaUM3bjdPRXdBeStRUjdDSG9mTEVVCndYa3FnQ2ZRd1dzVWNFWkQySGhI
            elJhSnZDQi92bFQwVHpKZGliRWJwMUkKLS0tIGJFUjRJRWVLUGF0bGtVS3JEVy81
            UGkxbmpkcG05bE5zd1J3Smc1TitDcEkKLyajdsAgh1beroZXgTxriiGEDRFeIVAe
            aIq48O9jJC10fpM9iZVr72Zpqjqfm4j+v51wut8XrMV33NvyfhkhCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T16:52:47Z"
    mac: ENC[AES256_GCM,data:iKQmUSQ6ZSopmBQ0DhyRee5pjgOL0Nz5mDLo4+TAyRdm2jFtXZUgXVIc5Mz7+Uou0qWLjvcUSd52V5iQZy+mpcxM2DNXTlYOSDUDHnF+92+w7GkCCoZUiGqCKa6nv0ugGkWFSYHem6tToQ1gjNLbjhAK/IiV8mVqrZD3kQIoLYg=,iv:C37oycyxUmgLuYdzc0GqNGN/GXeXRcCNUKnudmqeWu0=,tag:YDaH/hzfIf7blmQyGOvMOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
