# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sq207C/gB23gXsXs7rZdR4SMHNY=,iv:TWkOO6H+9zFdBtM/nTGUCFyIBh8///LXvAJR6vNXb28=,tag:PlD5lOxd/JWjw1M5y44I3g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:3xPHf/MV0wjU7RXhCelZKe+ZKc7KljCZWEdoRcqK9THIa/mXFg==,iv:3Vff9LkX1esVlwtYLXASxyepgoMU9OB+2quWbZSxtl8=,tag:dW3nimh+UDUkLSTeDjFAKw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JpFagUdORlRnznMMgvQ=,iv:XiZRmyvdaHaJKmZon1QPWGIIwGL/ZLUHgrowMUC7j2M=,tag:jYzxbxsrqseICZgBQ8xl5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0czVZdVljV2hTbXJObUs4
            K045VHdhWHFNYVNxYTFSQ3BNajZDR0lvZVZFCmhyLzM2WVcwNkdEMFJncWhwL0t5
            SmovVUZJWVJDd1BzaHdyOVAwblBFZGcKLS0tIDFoeVFKcUZGeDYvcGNraGZrSzcw
            QVk3cWRNY1VDRURKWjhFVXdHdVp2R2cK4NlRC/uArkoRsbb1xksrFJvh8GlPofpY
            4XSvBM3leaEA0q3kzjOO0x233+ZRg5c77t7w9UlD0kKlMVHx2HY3dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-26T20:58:27Z"
    mac: ENC[AES256_GCM,data:A/S+PYZ5onp/ljsdrJtN8ADeTb0V7hJ2v9Z3xuc2rA8KgA4cbdVhamf9Jxvpk9cBIE2VKBpRUBADyLjgs5ldXZF0ytRoD5GLNGkhr4TGRWzfMacQzUROX6FO7U8JFkpEallzemwJIIzk0yAoAeYmByCESORKcMs+Ek2jTZwVIf8=,iv:rF8282UrpGqkUbn/Gst9zxmiFVjanwiCr/OphBROq+4=,tag:565rXAaqJu2q7zqG5EtWxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
