apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://balai-dc.ninhu.xyz:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.43.0
- name: Prometheus-balai
  type: prometheus
  access: proxy
  orgId: 1
  url: http://balai-dc.ninhu.xyz:10090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.43.0
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://balai-dc.ninhu.xyz:10086
  database: mydatabase
  jsonData:
    httpMethod: GET