---
kubernetes:
  children:
    master:
      hosts:
        opsm-1:
          ansible_host: 192.168.89.15
        opsm-2:
          ansible_host: 192.168.89.16
        opsm-3:
          ansible_host: 192.168.89.17
    worker:
      hosts:
        opsw-1:
          ansible_host: 192.168.89.23

proxy:
  hosts:
    portal-proxy:
      ansible_host: portal-proxy.ninhu.xyz
