# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:+CMwycQMBoVnVMiylVxDNJBBapu0vea3dLM2vt1vqm4oL8xY+w==,iv:n+7MWO/zk39YgIxYkU4MjHeNFKDMxZZYIpHUpEw6KUA=,tag:DrMon/Bn17H4W/MHDNKcMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qhgwj6mzm5z5frl3zxr933l5qgznk7x6hcpaejhxja8q8a2vuwq2wdax2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVm5LaFIyTDR1b1R3RnF0
            dkxFSll3MkJ4TFJyc1hHMWkvSTRkRWxMc1g0CkI3NWJMbmo1NlEvN013d3lRRHRH
            R3JFY0x0SG5ydDk5SGdXT3FUaTdDZU0KLS0tIDI5cmROVmx3Z3ZSK3FQVm1QaGlE
            Tm1aUWc0U281Y0dGajhnVGJMdU1xNmsKR1oXukVjMq8FdzS3KJiLzJ2AcbHT1DWB
            NJ1nJQTFFkGwlvn4PD4auqy8sUjippEIDIhpUEE/mrrBhtKSVfCU5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T16:52:47Z"
    mac: ENC[AES256_GCM,data:NhBGGebcQYZ4NLwoJtVmyXuVqmXpXi3QHMvo1Gwh1rlfPm9SsFxd0VMiYx0swYDUQGFc2pNSgGuNA/See3N36Axs7el9vborUon9JGXKsmB/C4MfSCKWjTngtbJhHxntFdGxINl7lO0s7CZlonzjyM3R+Hx73qadqr76qOgl+p4=,iv:veDYqJuZHGKvYLvswMCThGjBka4utad9YOCMHnr/TMY=,tag:a2F5DS1ZGe8JjjRBZY8CAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
