# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:s5w/D5hQEY0VOCpMP2UufUIw74LAXnbEJTfAuYh9eIZC1XT9uQ==,iv:ClQkpdPZZTzKw8gehoruGinwV1ZExweXOXPus++lknU=,tag:tZIUuepCwBpMC04b9ELYCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK0pLcFRBUWhsUDNHWHFL
            L1o5MXBOaUY1MGE0WGxsZ00xcjUxME1JUXlnCmtFbjNGMTZqM0RjTkFPNy9LbG5W
            QzBGcjNaeitkdzQrcUovL2Q0ekFoTXMKLS0tIFNvMmpWUEN3NkJyVyt0NHlkSU5i
            QlhOOWFwUWxUOE5DSmFGb2hoNU9XQXcKtp8BbosMOwx5refUvLysvjfSc5MzQl7v
            h2lzzwNiUQvI1tuTLJ+6ogM2MbTTrBEPsgeyZar4zZYNyvUV1fsatg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-26T20:58:27Z"
    mac: ENC[AES256_GCM,data:thZKNRlLMTAYnb9SjLkfv5gWD70qvVAtkaSlUaslRy9X0l9isMIAxbu1LaMtHaMzoeFsyRztagPR5+YM/CUeM805HTVWXUafJxP1wCXfG1IsGbQU9pWaOLj8fqyh3KL8egk2C545WHVXFeUtje6Apk63pxodirMNTEhuQmWFM5I=,iv:mNXjMadd6VZzvKhIpnP2pj2Spv90xvKm+hjlYW01dbg=,tag:jOVtAHdkCb8Tz+UbftCzvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
