# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:TCIRBVV9mTn8VpIk1RRat2MAr1Q=,iv:seyIXV967XpkVwzs5NwZ8pW0+Er7y5rhuEQ8lunn9Ew=,tag:u6Ti82KDb7qpGhYuUF1CgQ==,type:str]
    api-key: ENC[AES256_GCM,data:EiG+L9Bx+RwZIqXylrzF8w8FIYCv1b5GVfh2qSCf8e08vQ39nQ==,iv:HLmM7dpRLCpx3AWW+fSSa0ATw2M/YVeaczcipGY8/hc=,tag:cfhqf8sY58fqaMnMr5v8sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qhgwj6mzm5z5frl3zxr933l5qgznk7x6hcpaejhxja8q8a2vuwq2wdax2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVkhzZThML0liWE03dkto
            T1Q1MHhqcjh0bC9YTUZ6RGdlalBRWDl0VWpRCjhaL1F3SkNJMWV5Z0tPdjd4emlI
            VGM2VU1kaGxWUDJHcFByRWQ5Z1FzaU0KLS0tIC9BUFR2VE1yUXAza256T09TdXJN
            clNmeUwwcFA2dVFzMUMwbVAySURjQmcKy9Psi/ekAmDL8rili8B77T6CKKZLbfq6
            edrpw0wah2pB2FrbaCajE3oyy/R7gQw/qUpZMcd4zLK7WGTDL9DSXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T16:52:47Z"
    mac: ENC[AES256_GCM,data:CR2UxcnvgSI/08zcy+DvlDXtnXrQHu86Cb0A8yT6r1SL4mapuCSeYKS/8B6HpROvvOJKe7R7rT7DvL1Ge0fJQINynAxkUVeul6N6NHsPsRMkEKn2jpA6gJlWLrBv65iO5S0Ux4jST4sqBygFAmmYJVt/IkUfmNMB1vqlFDf3foo=,iv:eEiSfg186v/dwg3rWpYbL5ur7D9hgAkeENmAv3Rnp2E=,tag:Fph5qhye9bD8D5hXQkWsXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
