# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:UjTWF64rbvDXlL73nh7ETuUn2hM=,iv:b5Sc4yg7xxobkdaCZgjhZOO5eycDNMpqKb/HPm3M5w8=,tag:7gbZoszcNjAQ1VbEGSnypw==,type:str]
    api-key: ENC[AES256_GCM,data:QtbXeSLN3bBlqJ3Vzns3PHAZ5vwPCn2O2a6t+1afLJlA0HW/Sg==,iv:xd1tvomUkrqZxuXx7JQDaG2dUeflDB2P3auUo31O05A=,tag:+EnroJFyDv6gTn0Z3x1Kzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZG9lZDYrN2hYL2gyS0FC
            RHlWKzlBVlQyOUIxYWl6M3dWb1RSVzBtSWxFCnVlU0dGeFdLOGt3MXhQNjhORHh3
            cWErODVlQy9uZnBLTTFWWWdQM0tmZ00KLS0tIFJCQ2srRHNHTUJDbTQ4d2hZZVMz
            WXJ3VXhJL3RUZVV2dW1UN0xlMm01OEUK9kUAdzGb6iLmV8bQE26p6S6fBsvRz9X+
            wC+fPVj97p2bn4ZTiUK3wHL5kddIh3bdxrK85YZQLfnhkP/iFjaTyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-26T20:58:27Z"
    mac: ENC[AES256_GCM,data:HhHqWbwErIN4WFq3tld6eGr4/aICH2kYfGWA7qNYeEw6ktj8+SJAfv3AuX5XKlKNT9TkCoodUf/b8I61lymfRnOyKG+2fNPm5Wbs8Hz/HX/4f1cTPv0VERQmqK2lTpcrYF1O+Qnw34FwImZOtu7X7jahXX8EaJyJQrpw/PS3UNY=,iv:oCBzFaIbXNDPEW+4++reN1fHs8d5lJt5bizYKAFjFSw=,tag:NR3U2CRNI1swzhMt9+YQ1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
