# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GqH760DAfP50,iv:YKrmjBYw9fSRMZ5tlx+GxkZGzQsiykg8mKNrH7c32uE=,tag:nfMxv/7nYWp5TcieZBDuRQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yla5FEwVH7s2flzgvK/lmUy9AHI=,iv:utSTJafLqXYEeV0/taFbZoHt1R2UCBM1OWzRh41csyo=,tag:pYwgVxHwqK/QGJ7bJ+O9jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qhgwj6mzm5z5frl3zxr933l5qgznk7x6hcpaejhxja8q8a2vuwq2wdax2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaE5nQjBsTzF5Vyt3cmN3
            YnhhV293bzNwcDBMNWsyejd1bkNvd3p4M1VjCmExdnFGOGFqTHowL1EvVS9rbS84
            TDRJVlQzWGZDOGp1VDVQMzJVKzV0RDgKLS0tIFI4ZmM5QTBmWlRTWjdUL09oV2FO
            U0txakJFQWdGdU11ZDhwUS83anRlT0kKoonE8Ti7n1rXHDqvKtvDZe/Hr7LK9QrV
            pvs/YBYgVhbE9f5oWTi8hxQ41ADn4eJojb/KOTVb2eHdUBxM8acaUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T16:52:47Z"
    mac: ENC[AES256_GCM,data:1BnDQS82f7+8MY4gtrrHrv7PGGODzX60GOXwT1guJXlw/nQvEY7zrgH28y43fM/rVr0gu0TKf6iZE9P/PjKQD1cWJH6jXKFYYEOxjM4n+2QH5JmVjlDwAXFJQnw6URyMuS4qSIBsBlqrdnJZrCdxdksMJHragePE36dBaqJbSvQ=,iv:bawwzZLN2Ni9a68LuJgxeLfHvjgw8KqxJgZjACrzF6s=,tag:Cw3uBgjUcSJfbnta/n3KEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
