# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XAFezRmVSz7B,iv:1K7K6RSn2PHxJAQnCADgYOs1Dku/FJi+UdUOmONjb+o=,tag:RJh1ZsfgiMU+GQC2sBvQnQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oKIjt8Z6q7ywUFlEoqRJrAoI+t4=,iv:TNKVzgM98fck2jJ/e1u40ItgiRGPNQ46ZsT+rdtWtVE=,tag:qNuPEJ9xqR8+m1IYcGqCqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcjN3VW9CanNLRGFiVkR0
            U2pzTmFTaFRSaEIvMnJVcGUvOGROV0g4eFh3CkZhWEpBdVZSbnhTYk44Y2hTaVRH
            dFp2SDRxa1UwbHJqdGovTXNVeTJFUVUKLS0tICt6QUxZZkNFWWhzcTNsczZrM3lk
            dzVZU0N3UVV1QzNuUHhybC9JSkZWeEUKFfKspvcl5SqqHtRGuY2+HafSPOi9izOZ
            QH8J067vhGJ9GIKKwy++PQdd1VYK1XHCOjE6Ela/r0c/dYDNAboJ8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-26T20:58:27Z"
    mac: ENC[AES256_GCM,data:xvoOI+VU6jL4Y2MsTPVPOd0aqaxBnJacJyc54ocYJExjSmC9CO/tu6ojm+Yy4aGFc8UVAw9CPqj9fEwYNg7vo7hpdDeccSqd2bguOhNo4v82ivnIaeBilKIhTfgfHDLxm+h7K7/koxrSOXl6Cb7FuSK0H6xHCByj+9cd5Y9vo78=,iv:3hksiIYsGsCNeMKwJM8M45hEQw1YxPg94WFBNGxlJqU=,tag:30wPb4TFO4L6oHPHJEeVRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
