apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:zBako2IgA2GrrExtgCOEn80VWZo3G19eQ5iFoH+Q4LzMi/dEiA==,iv:SyLkYJ6Cm/HXg/DptwCrH/UxxK/8yDdD138v0CajX6M=,tag:O248zKCrBc5hcR1BZM4gtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vggkcg3qnhzprann40zldc92nrv3ps5mpg7e4vl5ggllrgtjxucsw9ugyc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSUV1TXRYOEZFajNhTVdK
            c0c4QXo3cm1HbmpVbEc0L25UbG1rZmxuRVZJClhBSzJGbjdINFl1azdMTEUvRnpr
            S1BCckNCT0RqWGlmaitwVmlmY05lOTgKLS0tIGNEWEFTVzZBM1ZjL3ZEUFlOakxB
            YjNQbWhROWlzcldKTmZtV2pZR1hOSWcKKVO+huh3AzQvfQrgMM11yuPFsr3KisXc
            Kc32quhiJzBxDhQhON+Ikq4aegvaACFwM3bNcTioeZJpSwAfygzJPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T22:18:26Z"
    mac: ENC[AES256_GCM,data:6SWqAjrqoD5+OgmZkzH755oyGoIv28Ea73H6IwQAkCiGdTYGbaar/nf3r8OLdiUPzD9hFlEMuOO5HWsrUKkS4m1rN5GhZsaSrPFRc7hxJfYdFeA/7sYeb0jt1wyJ59BjJGoqRBlPvn6jRPvK6RG8hDa3vt9Uk3PYKxJIABbPCVc=,iv:9EU4M/nlxGbJg1h2KNYY1Sh35WYHn317UfcYkA88jvU=,tag:3LAc7Hbpo2LfhHHzAqpUtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
