kind: Secret
ansible_user: ENC[AES256_GCM,data:nE4/dAE=,iv:CIULoKs+6lhL3r4ht85K9MxxGpHkqsCq1UkDVqxdX60=,tag:1sgRRJqwBkqOmj5IdK0Otg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMWhGNGlhNnhHdmFGOXdJ
            VjBRZnBPaWE3QitqT0xFeU5CNjErL3E1OEJ3Ckk4b1dieUg3ZVFvcTRpY0NOby84
            SGZiNUNMZW9TWkZROUR3emZYK2tWcmcKLS0tIGtycG9JUnFqZ1FDanlHNmpGSjNj
            RXhkQ3BrSkVUYkhyZUIyUEo1UEd2N0EKTHd3g6qnemAX6OH9JuZ91XYUiVYMhocW
            1/G8k9nSQGNnClZOWm7vNBqERpRBQ8a+FeCQ/mdjVvcHfzgTiPjc3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-26T20:58:27Z"
    mac: ENC[AES256_GCM,data:J2u9IhnGuQab1a77kReiEQ3Fa9i99kinyUSjLNZ3gk8Hm6mn5Idn3Kk+KCsZ2JbqdWxNwpNTPB7itjbF5bpVuMUVCEBiXJQ5aLFGx6aX5fZpXEf44OjUZtnbR4SCdoTr8ypktnizJI8Zv1GOwke1E/j+srI4+nbFCYqTTgTemHw=,iv:ui/nspHp/EyveYAU4su8n5TH0FnQQHv8YoDoqa+d3kU=,tag:/Kl/D+V71VZRhUdK+b+tzA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
