kind: Secret
ansible_user: ENC[AES256_GCM,data:bc+gvLef6xU=,iv:rZbW968PD1RIf9eNs9umH2ISln+1r5lHz6nhmOCHWD4=,tag:MouVDCvfNBYFrDRTZyV0iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qhgwj6mzm5z5frl3zxr933l5qgznk7x6hcpaejhxja8q8a2vuwq2wdax2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRUxGRys4ZTlyZmNvZy9x
            dm9XOWdoWDdEc2c2NWpxUmRxUVVGQjJqdGdBCnNPckRDRExWUk8wdmdwY0ZzMU1W
            RFAzRFFaT2hhcVR2T1c2aGlxWTUxcmMKLS0tIGJveXFJWkcyaGpWUG1yazMycDF0
            VFA0OUZiZzQyMC9zR2xETUZZd29TMmsKg3s0xvkwSb7/TfmqcfdsIRAP9j48qqo+
            uSIk5N/5vgNc27DCZ1jMhNvy8IaBPPt1S5kbbbI56BCVHblTZbUYRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T16:52:47Z"
    mac: ENC[AES256_GCM,data:9jME93xyj55hqwoZOBkeOlXvRLzeEyarUYjwtrxSi3xQM3fIMxRBSVkFgKmbBEAtT8OMO1Ek8o+pI6SN4XdgZ561kj5FxDw/R+75Bf/rL6z7auh4cR7JGcXzZpT1SMuO+IqWG4n0ZVdl0sYhHH6IoCWWRbb1lENJkSb6IRCykB8=,iv:K6Pl6rTu8eNagmQE8wv9xecI9ARElA4/g+hxji6Y4U0=,tag:ibOApoJN4Mw/uybN3Dkx1g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
