---
- name: "Install the reverse proxy"
  hosts: proxy
  remote_user: "infra"
  become: true
  become_method: sudo

  tasks:
    - name: "Include nginx role"
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - nginxinc.nginx
      loop_control:
        loop_var: role
