---
- hosts: prometheus
  remote_user: "infra"
  tags: prometheus
  tasks:
    - name: "Include Role Prometheus"
      include_role:
        name: "{{ item }}"
      loop:
        - prometheus.prometheus.prometheus
