---
- name: "Configure base for all servers"
  hosts: all
  remote_user: "infra"
  become: true
  become_method: sudo
  tags: common
  roles:
    - nignu-common

# Install Node Exporter on all nodes
- name: "Install Prometheus Node Exporter"
  hosts: all
  remote_user: infra
  become: true
  tags: node_exporter
  pre_tasks:
    - name: " Create node_exporter dir"
      ansible.builtin.file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root

  tasks:
    - name: "Include roles prometheus"
      include_role:
        name: prometheus.prometheus.node_exporter

- import_playbook: prometheus.yml
- import_playbook: nginx.yml
