# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "hyperion.ninhu.xyz:10090"

  - job_name: "cadvisor"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - "cadvisor:8080"

  - job_name: 'node'
    honor_labels: true
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "hyperion.ninhu.xyz:9100"
          - "opnsense.ninhu.xyz:9100"
          - "orion.ninhu.xyz:9100"
          - "osc.ninhu.xyz:9100"
          - "psql.ninhu.xyz:9100"
          - "rpi.ninhu.xyz:9100"

  - job_name: 'netdata'
    honor_labels: true
    metrics_path: '/api/v1/allmetrics'
    params:
      format:
        - prometheus_all_hosts
    static_configs:
      - targets:
          - "hyperion.ninhu.xyz:19999"
          - "opnsense.ninhu.xyz:19999"
          - "orion.ninhu.xyz:19999"
          - "osc.ninhu.xyz:19999"
          - "psql.ninhu.xyz:19999"
          - "rpi.ninhu.xyz:19999"

  - job_name: "postgres_exporter"
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
    static_configs:
      - targets:
          - "psql.ninhu.xyz:9187"
