---
nginx_vhosts:
  - listen: "81"
    server_name: "metrics.ninhu.xyz"
    state: "present"
    extra_parameters: |
      location /nginx_status {
        stub_status on;
      }

# Prometheus
  - listen: "80"
    server_name: "prometheus.ninhu.xyz"
    state: present
    return: "301 https://prometheus.ninhu.xyz$request_uri"

  - listen: "443 ssl http2"
    server_name: "prometheus.ninhu.xyz"
    access_log: "/var/log/nginx/prometheus_ninhu_xyz_access.log"
    error_log: "/var/log/nginx/prometheus_ninhu_xyz_error.log"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      ssl_certificate     /etc/nginx/ssl/server.crt;
      ssl_certificate_key /etc/nginx/ssl/server.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
      location / {
        proxy_pass http://portal-proxy.ninhu.xyz:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

  # grafana
  - listen: "80"
    server_name: "grafana.ninhu.xyz"
    filename: "grafana_ninhu_xyz_80.conf"
    state: "present"
    return: "301 https://grafana.ninhu.xyz$request_uri"
  - listen: "443 ssl http2"
    server_name: "grafana.ninhu.xyz"
    access_log: "/var/log/nginx/grafana_ninhu_xyz_access.log"
    error_log: "/var/log/nginx/grafana_ninhu_xyz_error.log"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      ssl_certificate     /etc/nginx/ssl/server.crt;
      ssl_certificate_key /etc/nginx/ssl/server.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
      location / {
        proxy_pass http://balai-dc.ninhu.xyz:3000/;
        proxy_set_header Host $host;
      }
      # Proxy Grafana Live WebSocket connections.
      location /api/live {
        rewrite  ^/(.*)  /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $http_host;
        proxy_pass http://balai-dc.ninhu.xyz:3000/;
      }

  # cadvisor
  - listen: "80"
    server_name: "cadvisor.ninhu.xyz"
    filename: "cadvisor_ninhu_xyz_80.conf"
    state: "present"
    return: "301 https://cadvisor.ninhu.xyz$request_uri"
  - listen: "443 ssl http2"
    server_name: "cadvisor.ninhu.xyz"
    access_log: "/var/log/nginx/cadvisor_ninhu_xyz_access.log"
    error_log: "/var/log/nginx/cadvisor_ninhu_xyz_error.log"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      ssl_certificate     /etc/nginx/ssl/server.crt;
      ssl_certificate_key /etc/nginx/ssl/server.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
      location / {
        proxy_pass http://balai-dc.ninhu.xyz:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
