# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PO3YTY/spSrrXVi+cXOhQY2uZwSMnZBRiGHZTiIvavO+7k+TMm+cqA==,iv:SX96j4Vx4so2nBslOiZ2H8UPuQaKc6M+Gy4VAQsSSYo=,tag:4hoyDPgQ1yRBkoKOVbalbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm042na3tuevpk6hu2qlhv75ue0yh4fl552tlwkfsy4y7r59f0sd4sdcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aUdyR2NZTUllOUtySk42
            Y3phRlM3M1ZsNDNVdk5KRzNnWkxCVUtydFRJCm0rT2ZlSlFlWE1EbWw5REpOV0JM
            WHh0VmN6T3BBZ0pqZkd4NHJRejNtSTAKLS0tIGFwZmxFUE9NRUY2VGVueENQSC8v
            YWlhUFJTMU5BbWhHUkFyS0k5L0FBOUkKZ6sd05/old7FEfAF0oofKR1d6agBTTrX
            NoMnoWXXUTMCchCvPQ1dcnHVMplQSMKILacajTbDfFah6UKrQmkWNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-26T20:58:27Z"
    mac: ENC[AES256_GCM,data:AJHpjo1cV1ruKkTN0I0iVwCswHq7VHc5PeYNAL6xRv6vwSxdxxl/Q0yYpWWy+YsaKaIZ7/kpUBbvn2au8xm0mFYF5/CUSZ/FpdyjIkQK+FvO6hugBgu5J16bVLTsGah9DYiKwkFahX40cpnuZPIOqfCjff8qIEfVltIJy4VWCZE=,iv:aVGWMD4lyZI68Nnr73jt8lh5iCy+8tJ4NecQGwoJM78=,tag:UaFL5ZegyeVLZHzja9pYQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
